### ISSUE TITLE
/usr/local/bin/tsserver-wrapper

### ISSUE THREAD

**Issue by cj** [jose-elias-alvarez/dotfiles#1]
Thank you for this awesome nvim config.

Can you provide me with your /usr/local/bin/tsserver-wrapper please, not sure what I need for it.

Cheers!

**Comment by jose-elias-alvarez** [comment]
It's super simple – it's a Bash script that wraps `tsserver` to suppress an irrelevant warning message that shows up in LSP logs. I do a distressing amount of LSP debugging, so I want to keep my logs clean, but if you don't care, you can delete that line entirely and everything will work the same. 

Either way, here's the script:

```sh
#!/bin/sh

exec tsserver --npmLocation "$(which npm)" "$@"
```
